# -*- coding: utf-8 -*-
"""Generate JyPackets.g.cs from the Nuitka constant pool (analysis/pools.json).

Source indices in the __main__ pool (verified byte-level):
  174 DMOC 582B  op=0x10000014 教师将关闭您的计算机   -> 关机
  176 DMOC 582B  op=19        黑客将重启您的计算机   -> 强制重启
  175 DMOC 582B  op=0x10000013 教师将重启您的计算机  -> 提示重启
  177 DMOC 582B  op=2         黑客将关闭您的应用程序 -> 关闭所有应用程序
  169 notepad launch, 893B
  183 cmd.exe /c , 565B
  204 cmd.exe /k , 565B
  199 unlock 43B (op=5)
  184 zeros 316B ('01'@307)   200 zeros 994B
  168 msg header 12B (datalen 0x36e)   198 msg header 12B (datalen 0x39e)
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
# NOTE: analysis/pools.json (reverse-engineering data of the original program)
# is NOT part of this repository. The generated JyPackets.g.cs is committed,
# so you only need this script if you want to regenerate it from private data.
POOL = os.path.join(HERE, "..", "..", "JiYu-killer-archive", "analysis", "pools.json")
OUT = os.path.join(HERE, "..", "src", "JyPackets.g.cs")

NAMES = {
    174: "DmocShutdown",
    176: "DmocForceReboot",
    175: "DmocTeacherReboot",
    177: "DmocCloseApps",
    169: "NotepadLaunch",
    183: "CmdC",
    204: "CmdK",
    199: "UnlockNet",
    184: "Zeros316",
    200: "Zeros994",
    168: "MsgHeader4605",
    198: "MsgHeader4705",
}

with open(POOL, encoding="utf-8") as f:
    pools = json.load(f)
main = [p for p in pools if p["name"] == "__main__"][0]

lines = []
lines.append("// <auto-generated by csharp/tools/gen_packets.py — DO NOT EDIT>")
lines.append("// Byte-exact packet templates recovered from the Nuitka constant pool of")
lines.append('// 河豚反极域 v2.1.1 (__main__ module constants in analysis/pools.json).')
lines.append("namespace JiYuKiller.Core")
lines.append("{")
lines.append("    internal static partial class JyPackets")
lines.append("    {")
for idx, name in NAMES.items():
    v = main["vals"][idx]
    h = v.strip("'") if isinstance(v, str) else v
    assert isinstance(h, str) and len(h) % 2 == 0, f"idx {idx} not a hex string"
    b = bytes.fromhex(h)
    lines.append(f"        // pool[{idx}] {len(b)} bytes")
    lines.append(f"        public static readonly byte[] {name} = H(")
    chunks = [h[i:i + 64] for i in range(0, len(h), 64)]
    for n, chunk in enumerate(chunks):
        prefix = '            "' if n == 0 else '            + "'
        tail = '");' if n == len(chunks) - 1 else '"'
        lines.append(f"{prefix}{chunk}{tail}")
    lines.append("")
lines.append("    }")
lines.append("}")
lines.append("")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8-sig", newline="\n") as f:
    f.write("\n".join(lines))
print("wrote", os.path.normpath(OUT))
